project/login/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.http import HttpResponse

urlpatterns = [
    path('',views.home, name="home"),
    path('login/',views.loginpage, name="loginpage"),
    path('logout/',views.logoutuser,name="logoutuser"),
    path('register/',views.register,name="register"),
    path('deleteMovie/<str:pk>/',views.deleteMovie,name='deleteMovie'),
    path('updateMovie/<str:pk>/',views.updateMovie,name='updateMovie')
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('login.urls'))
]

project/login/models.py
from django.db import models
from django.db.models.fields import CharField


class Movie(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.CharField(max_length=200,null=True)
    name = models.CharField(max_length=200, null=True)
    genre = models.CharField(max_length=200, null = True)
    release_date = models.DateField(null=True)


    def __str__(self) :
        return self.name

project/login/forms.py
from typing import OrderedDict
import django
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

from .models import Movie

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

    
class MovieForm(ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

project/login/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import Movie
from .forms import RegisterForm, MovieForm
from .filters import MovieFilter


def register(request):
    if request.user.is_authenticated:
        return redirect('../')
    else:
        form = RegisterForm
        if request.method == 'POST':
            form = RegisterForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request,'Profile Created')
                return redirect('../login')
            else:
                messages.info(request,'Something went wrong')
        context = {'form':form}
        return render(request,'login/registerpage.html',context)

def loginpage(request):
    if request.user.is_authenticated:
        return redirect('../')
    else:
        if request.method=='POST':
            uname=request.POST.get('username')
            pword=request.POST.get('password')
            user = authenticate(request,username=uname,password=pword)

            if user is not None:
                login(request, user)
                return redirect('../')
            else:
                messages.info(request,'Username or Password is incorrect')

        return render(request,'login/loginpage.html')

def logoutuser(request):
    logout(request)
    messages.info(request,"Logged Out!")
    return redirect('../login')

@login_required(login_url='../login')
def home(request):
    all_movies = Movie.objects.all()


    usr = request.user.username
    form = MovieForm()

    myFilter = MovieFilter(request.GET, queryset=all_movies)
    all_movies = myFilter.qs

    if request.method == 'POST':
        post = request.POST.copy()
        post['user']=usr
        form = MovieForm(post)
        if form.is_valid:
            form.save()
    context = {'all':all_movies,'usr':usr,'form':form, 'myFilter':myFilter}
    return render(request,'login/homepage.html',context)

@login_required(login_url='../login')
def deleteMovie(request,pk):
    movie = Movie.objects.get(id=pk)
    if request.method == 'POST':
        movie.delete()
        return redirect('/')
    context = {'item':movie}
    return render(request,'login/delete.html',context)


@login_required(login_url='../login')
def updateMovie(request,pk):
    movie = Movie.objects.get(id=pk)
    form = MovieForm(instance=movie)
    usr = request.user.username
    if request.method == 'POST':
        post = request.POST.copy()
        post['user']=usr
        form = MovieForm(post)
        if form.is_valid:
            movie.delete()
            form.save()
            return redirect('/')
    context = {'item':form}
    return render(request,'login/update.html',context)

project/login/templates/login/delete.html
{% extends 'login/main.html' %}
{%block content%}



<form action="{%url 'deleteMovie' item.id%}" method="post">
    {%csrf_token%}

<div class="card">
    <div class="card-header">
      Warning!
    </div>
    <div class="card-body">
        <h5 class="card-title">Are you sure you want to delete "{{item}}"</h5>
        <input type="submit" href="{% url 'home' %}" value="Confirm" >
        <a href="{%url 'home'"> Cancel </a>
    </div>
  </div>

</form>


<style>
    .card{
        text-align: center;
    }
</style>
{%endblock%}

project/login/templates/login/homepage.html
{% extends 'login/main.html' %}
{% block content %}


<br>
<!--Render movie table-->
<div class="tableclass">
    <table class="table">
        <thead class="table-dark">
            <tr>
                <th>Title</th>
                <th>Genre</th>
                <th>Release Date</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {%for item in all%}
                {%if usr == item.user%}
                <tr>
                    <td>{{item.name}}</td>
                    <td>{{item.genre}}</td>
                    <td>{{item.release_date}}</td>
                    <td><a class="btn btn-sm btn-danger" href="{% url 'updateMovie' item.id%}" >Update</a></td>
                    <td><a class="btn btn-sm btn-danger" href="{% url 'deleteMovie' item.id%}" >Delete</a></td>
                </tr>
                {%endif%}
            {%endfor%}
        </tbody>
      </table>
</div>


<!--add a movie-->
<div class="inputMovie">
<form action="" method="POST">
    {%csrf_token%}
    <h3>Add a Movie</h3>
    <input type="hidden" name="user" value="username" maxlength="200" required id="id_user">
    <div class="row g-3">
        <div class="col">
            {{form.name.label}}
            {{form.name}}
        </div>
        <div class="col">
            {{form.genre.label}}
            {{form.genre}}
        </div>
        <div class="col">
            <label for="">Release Date (mm/dd/yyyy)</label>
            {{form.release_date}}
        </div>
    </div>
    <button type="submit" class="btn btn-primary" value="Delete MOvie">Submit</button>
</form>
</div>


<!--add filter-->
<div class="inputFilter">
    <div class="row g-3">
    <form action="" method="get">
        <div class="col">
        <label for="filterTitle">Filter by Title:</label>
        {{myFilter.form.name}}
        </div>
        <div class="col">
        <button class="btn btn-primary" type="submit">Search</button>
        <a class="btn btn-sm btn-danger" href="{% url 'home'%}" >Remove filters</a></td>
        </div>
    </form></div>
</div>

<style>
    body {
        background: #C4f4f8;
    }
    .inputMovie {
        background: #efefef;
        padding: 60px 120px 80px 120px;
        text-align: center;
        max-width: 500px;
        margin-top: 25px;
        margin: auto;
    }
    .col{
        margin:10px;
    }
    .tableclass{
        max-width: 500px;
        margin: auto;
        margin-top: 25px;
    }
    .inputFilter{
        background: #efefef;
        padding: 0px 120px 80px 120px;
        text-align: center;
        max-width: 500px;
        margin: auto;
    }
    tbody{
        background:#FFDAc1;
    }
    h3{
        text-align: center;
    }
</style>
{% endblock %}

project/login/templates/login/loginpage.html
{% extends 'login/main.html' %}
{% block content %}

<form action="" method="post">
    {% csrf_token %}
        <div class="form-group">
          <h2>Login</h2>
          <label for="exampleInputUsername">Username</label>
          <input type="text" name="username" id="">
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          <input type="password" name="password" id="">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
       <div class="form-group">
        <a href="../register">Click here to Register</a>
       </div> 
      {%for message in messages%}
      <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        {{message}}
      </div>
      {%endfor%}

        </form>


<style>
  body {
    background: #C5E1A5;
  }
  form {
    width: 60%;
    margin: 60px auto;
    background: #efefef;
    padding: 60px 120px 80px 120px;
    text-align: center;
    -webkit-box-shadow: 2px 2px 3px rgba(0,0,0,0.1);
    box-shadow: 2px 2px 3px rgba(0,0,0,0.1);
  }
  label {
    display: block;
    position: relative;
  }
  .label-txt {
    position: absolute;
    top: -1.6em;
    padding: 10px;
    font-family: sans-serif;
    font-size: .8em;
    letter-spacing: 1px;
    color: rgb(120,120,120);
    transition: ease .3s;
  }
  .input {
    width: 100%;
    padding: 10px;
    background: transparent;
    border: none;
    outline: none;
  }

  .line-box {
    position: relative;
    width: 100%;
    height: 2px;
    background: #BCBCBC;
  }

  .line {
    position: absolute;
    width: 0%;
    height: 2px;
    top: 0px;
    left: 50%;
    transform: translateX(-50%);
    background: #8BC34A;
    transition: ease .6s;
  }

  .input:focus + .line-box .line {
    width: 100%;
  }

  .label-active {
    top: -3em;
  }

  button {
    display: inline-block;
    padding: 12px 24px;
    background: rgb(220,220,220);
    font-weight: bold;
    color: rgb(120,120,120);
    border: none;
    outline: none;
    border-radius: 3px;
    cursor: pointer;
    transition: ease .3s;
  }

  button:hover {
    background: #8BC34A;
    color: #ffffff;
  }
</style>

{% endblock %}

project/login/templates/login/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Table</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Django Table</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="/register">Register</a>
            </li>
            <li class="nav-item ">
              <a class="nav-link" href="/login">Login <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/logout">Logout</a>
            </li>
          </ul>
        </div>
      </nav>

    {% block content %}
    

    
    {%endblock%}

    <hr>

    
</body>
<style>
  body{
    font-family: monospace;
  }
</style>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</html>

project/login/templates/login/registerpage.html
{% extends 'login/main.html' %}
{% block content %}


<form action="" method="post">
    {% csrf_token %}
      <h2>Register</h2>
        <div class="form-group">
          <label for="exampleInputEmail1">Username</label>
          {{form.username}}
        </div>
        <div class="form-group">
          <label for="exampleInputEmail1">Email</label>
          {{form.email}}    
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
            {{form.password1}}    
            <small id="passHelp" class="form-text text-muted">Requires 8 characters of letters, digits or special characters </small>
        </div>
        <div class="form-group"></div>
          <label for="exampleInputPassword1">Confirm Password</label>
            {{form.password2}}    

        </div>
        <div class="form-group"></div>
        <button type="submit" class="btn btn-primary">Submit</button>
        </div>
       <div class="form-group">
        <a href="../login">Click here to Login</a>
       </div> 
      {%for message in messages%}
      <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        {{message}}
      </div>
      {%endfor%}
    </form>




<style>

body {
  background: #C5E1A5;
}
form {
  width: 60%;
  margin: 60px auto;
  background: #efefef;
  padding: 60px 120px 80px 120px;
  text-align: center;
  -webkit-box-shadow: 2px 2px 3px rgba(0,0,0,0.1);
  box-shadow: 2px 2px 3px rgba(0,0,0,0.1);
}
label {
  display: block;
  position: relative;
}
.label-txt {
  position: absolute;
  top: -1.6em;
  padding: 10px;
  font-family: sans-serif;
  font-size: .8em;
  letter-spacing: 1px;
  color: rgb(120,120,120);
  transition: ease .3s;
}
.input {
  width: 100%;
  padding: 10px;
  background: transparent;
  border: none;
  outline: none;
}

.line-box {
  position: relative;
  width: 100%;
  height: 2px;
  background: #BCBCBC;
}

.line {
  position: absolute;
  width: 0%;
  height: 2px;
  top: 0px;
  left: 50%;
  transform: translateX(-50%);
  background: #8BC34A;
  transition: ease .6s;
}

.input:focus + .line-box .line {
  width: 100%;
}

.label-active {
  top: -3em;
}

button {
  display: inline-block;
  padding: 12px 24px;
  background: rgb(220,220,220);
  font-weight: bold;
  color: rgb(120,120,120);
  border: none;
  outline: none;
  border-radius: 3px;
  cursor: pointer;
  transition: ease .3s;
}

button:hover {
  background: #8BC34A;
  color: #ffffff;
}
</style>

{% endblock %}

project/login/templates/login/update.html
{% extends 'login/main.html' %}d
{% block content %}

<div class="inputMovie">
<form action="" method="POST">
    {%csrf_token%}
    <h3>Update Movie</h3>
    <input type="hidden" name="user" value="username" maxlength="200" required id="id_user">
    <div class="row g-3">
        <div class="col">
            {{item.name.label}}
            {{item.name}}
        </div>
        <div class="col">
            {{item.genre.label}}
            {{item.genre}}
        </div>
        <div class="col">
            <label for="">Release Date (mm/dd/yyyy)</label>
            {{item.release_date}}
        </div>
    </div>
    <button type="submit" class="btn btn-primary" >Update</button>
</form>
</div>
<style>
    body {
        background: #C4f4f8;
    }
    .inputMovie {
        background: #efefef;
        margin: auto;
        padding: 60px 120px 80px 120px;
        text-align: center;
        max-width: 500px;
        margin-top: 25px;
    }
    .col{
        margin:10px;
    }
    tbody{
        background:#FFDAc1;
    }
    h3{
        text-align: center;
    }
</style>
{%  endblock %}